In [ ]:
import torch
import torch.nn as nn

In [ ]:
d_model=6
max_sequence_len=11

The positional encodings have the same dimension dmodel
as the embeddings, so that the two can be summed. There are many choices of positional encodings,
learned and fixed [9].

In [ ]:
# pe= torch.zeros(max_sequence_len,d_model)

In [ ]:
# pe.shape

In [ ]:
pos=torch.arange(max_sequence_len,dtype=torch.float) #for sentence we have a sentence of 11len
pos

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
pos.shape

torch.Size([11])

In [ ]:
pos=pos.reshape(max_sequence_len,1) #can use unsqueeze too

In [ ]:
pos

tensor([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [ ]:
pos.shape

torch.Size([11, 1])

In [ ]:
even_i= torch.arange(0,d_model,2) #0 to dmodel with 2 steps

In [ ]:
even_i.shape

torch.Size([3])

In [ ]:
even_denominator= torch.pow(10000,even_i/d_model)

In [ ]:
even_denominator

tensor([  1.0000,  21.5443, 464.1590])

In [ ]:
odd_i=torch.arange(1,d_model,2)
odd_i

tensor([1, 3, 5])

In [ ]:
odd_denominator=torch.pow(10000,(odd_i-1)/d_model)
odd_denominator

tensor([  1.0000,  21.5443, 464.1590])

odd_denominator === even_denominator, so we can use either of them


In [ ]:
denominator=even_denominator
denominator

tensor([  1.0000,  21.5443, 464.1590])

In [ ]:
even_PE= torch.sin(pos/denominator)
even_PE

tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.8415,  0.0464,  0.0022],
        [ 0.9093,  0.0927,  0.0043],
        [ 0.1411,  0.1388,  0.0065],
        [-0.7568,  0.1846,  0.0086],
        [-0.9589,  0.2300,  0.0108],
        [-0.2794,  0.2749,  0.0129],
        [ 0.6570,  0.3192,  0.0151],
        [ 0.9894,  0.3629,  0.0172],
        [ 0.4121,  0.4057,  0.0194],
        [-0.5440,  0.4477,  0.0215]])

In [ ]:
even_PE.shape

torch.Size([11, 3])

In [ ]:
odd_PE=torch.cos(pos/denominator)

In [ ]:
odd_PE

tensor([[ 1.0000,  1.0000,  1.0000],
        [ 0.5403,  0.9989,  1.0000],
        [-0.4161,  0.9957,  1.0000],
        [-0.9900,  0.9903,  1.0000],
        [-0.6536,  0.9828,  1.0000],
        [ 0.2837,  0.9732,  0.9999],
        [ 0.9602,  0.9615,  0.9999],
        [ 0.7539,  0.9477,  0.9999],
        [-0.1455,  0.9318,  0.9999],
        [-0.9111,  0.9140,  0.9998],
        [-0.8391,  0.8942,  0.9998]])

In [ ]:
odd_PE.shape

torch.Size([11, 3])

In [ ]:
stacked= torch.stack([even_PE,odd_PE], dim=2)
stacked

tensor([[[ 0.0000,  1.0000],
         [ 0.0000,  1.0000],
         [ 0.0000,  1.0000]],

        [[ 0.8415,  0.5403],
         [ 0.0464,  0.9989],
         [ 0.0022,  1.0000]],

        [[ 0.9093, -0.4161],
         [ 0.0927,  0.9957],
         [ 0.0043,  1.0000]],

        [[ 0.1411, -0.9900],
         [ 0.1388,  0.9903],
         [ 0.0065,  1.0000]],

        [[-0.7568, -0.6536],
         [ 0.1846,  0.9828],
         [ 0.0086,  1.0000]],

        [[-0.9589,  0.2837],
         [ 0.2300,  0.9732],
         [ 0.0108,  0.9999]],

        [[-0.2794,  0.9602],
         [ 0.2749,  0.9615],
         [ 0.0129,  0.9999]],

        [[ 0.6570,  0.7539],
         [ 0.3192,  0.9477],
         [ 0.0151,  0.9999]],

        [[ 0.9894, -0.1455],
         [ 0.3629,  0.9318],
         [ 0.0172,  0.9999]],

        [[ 0.4121, -0.9111],
         [ 0.4057,  0.9140],
         [ 0.0194,  0.9998]],

        [[-0.5440, -0.8391],
         [ 0.4477,  0.8942],
         [ 0.0215,  0.9998]]])

In [ ]:
stacked.shape

torch.Size([11, 3, 2])

In [ ]:
PE= torch.flatten(stacked,start_dim=1,end_dim=2)

In [ ]:
PE

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0464,  0.9989,  0.0022,  1.0000],
        [ 0.9093, -0.4161,  0.0927,  0.9957,  0.0043,  1.0000],
        [ 0.1411, -0.9900,  0.1388,  0.9903,  0.0065,  1.0000],
        [-0.7568, -0.6536,  0.1846,  0.9828,  0.0086,  1.0000],
        [-0.9589,  0.2837,  0.2300,  0.9732,  0.0108,  0.9999],
        [-0.2794,  0.9602,  0.2749,  0.9615,  0.0129,  0.9999],
        [ 0.6570,  0.7539,  0.3192,  0.9477,  0.0151,  0.9999],
        [ 0.9894, -0.1455,  0.3629,  0.9318,  0.0172,  0.9999],
        [ 0.4121, -0.9111,  0.4057,  0.9140,  0.0194,  0.9998],
        [-0.5440, -0.8391,  0.4477,  0.8942,  0.0215,  0.9998]])

In [ ]:
PE.shape

torch.Size([11, 6])